services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: database
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
